<a href="https://colab.research.google.com/github/siddharthramagiri/Machine-Learning/blob/main/Na%C3%AFve_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Dependencies

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
iris_data = pd.read_csv("/content/Iris.csv")

In [ ]:
iris_data.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [ ]:
X = iris_data.drop(columns='Species') #['5.1','3.5','1.4','0.2'	]
y = iris_data['Species']

Splitting the DataSet into the Training Set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [ ]:
X_train.shape

(120, 5)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_predict = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy = accuracy_score(y_test,y_predict)
print("Accuracy : ",accuracy)
print(confusion_matrix(y_test,y_predict))

Accuracy :  1.0
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [ ]:
pd.DataFrame({'Real Values' : y_test,
              'Predicted Values' : y_predict,
              })

Real Values Predicted Values
47       Iris-setosa      Iris-setosa
3        Iris-setosa      Iris-setosa
31       Iris-setosa      Iris-setosa
25       Iris-setosa      Iris-setosa
15       Iris-setosa      Iris-setosa
118   Iris-virginica   Iris-virginica
89   Iris-versicolor  Iris-versicolor
6        Iris-setosa      Iris-setosa
103   Iris-virginica   Iris-virginica
65   Iris-versicolor  Iris-versicolor
88   Iris-versicolor  Iris-versicolor
38       Iris-setosa      Iris-setosa
92   Iris-versicolor  Iris-versicolor
53   Iris-versicolor  Iris-versicolor
140   Iris-virginica   Iris-virginica
40       Iris-setosa      Iris-setosa
72   Iris-versicolor  Iris-versicolor
135   Iris-virginica   Iris-virginica
113   Iris-virginica   Iris-virginica
42       Iris-setosa      Iris-setosa
126   Iris-virginica   Iris-virginica
112   Iris-virginica   Iris-virginica
141   Iris-virginica   Iris-virginica
76   Iris-versicolor  Iris-versicolor
5        Iris-setosa      Iris-setosa
109   Iris-virginica   Iris-virginica
134   Iris-virginica   Iris-virginica
67   Iris-versicolor  Iris-versicolor
57   Iris-versicolor  Iris-versicolor
86   Iris-versicolor  Iris-versicolor